// 
// Decompiled by Procyon v0.5.36
// 

package listenerFrameCartellaClinica;

import java.awt.event.MouseListener;
import javax.swing.JToggleButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.text.Document;
import utility.LimitedTextField;
import javax.swing.Box;
import java.awt.FlowLayout;
import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import java.awt.Container;
import javax.swing.BoxLayout;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JLabel;
import java.awt.LayoutManager;
import java.awt.GridLayout;
import java.awt.Color;
import java.io.IOException;
import java.io.OutputStream;
import java.io.ObjectOutputStream;
import java.io.FileOutputStream;
import utility.ControlloOs;
import oggetti.Paziente;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import java.io.Serializable;

public class FrameCartellaClinicaModel implements Serializable
{
    private static final ButtonGroup gruppoRegimeDiRicovero;
    private static final ButtonGroup gruppoProvenienteDa;
    private static final ButtonGroup gruppoTipologiaDimissione;
    private static final ButtonGroup buttonGroup_1;
    private static final ButtonGroup gruppoScreeningDolore;
    private static final ButtonGroup gruppoScalaDolore;
    private static final ButtonGroup gruppoFumatore;
    private static final ButtonGroup gruppoUsoDiAlcool;
    private static final ButtonGroup gruppoIgienePersonale;
    private static final ButtonGroup gruppoCaratteristicheDelSonno;
    private static final ButtonGroup gruppoStatoEmotivo;
    private static final ButtonGroup gruppoMovimento;
    private static final ButtonGroup gruppoAlimentazione;
    private static final ButtonGroup gruppoMinzione;
    private static final ButtonGroup gruppoAlvo;
    private static final ButtonGroup gruppoStomie;
    private static final ButtonGroup gruppoIncontinenza;
    private static final ButtonGroup gruppoAllergiaIntolleranzeAdAlimenti;
    private static final ButtonGroup gruppoAllergiaAlLattice;
    private static final ButtonGroup gruppoAllergiaAdAltreSostanze;
    private static final ButtonGroup gruppoAllergiaNotaAFarmaci;
    private static final ButtonGroup gruppoAssunzioneAnticoagulantiOrali;
    private static final ButtonGroup gruppoAssunzioneImmunosoppressori;
    private static final ButtonGroup gruppoAssunzioneIpoglicemizzantiOrali;
    private static final ButtonGroup gruppoSomministrazioneInsulina;
    private static final ButtonGroup gruppoFavismo;
    private static final ButtonGroup gruppoAssunzioneAntiiperestensivi;
    private static final ButtonGroup gruppoAssunzioneDiuretici;
    private static final ButtonGroup gruppoPsicofarmaci;
    private static final ButtonGroup gruppoTiroide;
    private static final ButtonGroup gruppoCondizioniGenerali;
    private static final ButtonGroup gruppoFunzioniCognitive;
    private static final ButtonGroup gruppoSensorio;
    private static final ButtonGroup gruppoCute;
    private static final ButtonGroup gruppoAltreEventualiAlterazioniCutanee;
    private static final ButtonGroup gruppoMucoseVisibili;
    private static final ButtonGroup gruppoAlterazioniDelRespiro;
    private static final ButtonGroup gruppoPortatoreDiProtesi;
    private static final ButtonGroup gruppoAnamnesiFamiliare;
    private static final ButtonGroup gruppoScreeningStatoNutrizionale;
    private final CardLayout cardLayout;
    private final CardLayout cardLayoutTextArea;
    private JTextField textField;
    private JTextField textFieldDirettoreResponsabile;
    private JTextField textFieldProvenienteDaAltro;
    private JTextField textField_Cognome;
    private JTextField textField_Nome;
    private JTextField textFieldLuogoDiNascita;
    private JTextField textFieldProvincia;
    private JTextField textField_DataDiNascita;
    private JTextField textField_CF;
    private JTextField textFieldTemperaturaFebbrile;
    private JTextField textFieldFPerMinuti;
    private JTextField textFieldPressioneArteriosa;
    private JTextField textFieldSpO2;
    private JTextField textFieldFrequenzaCardiaca;
    private JTextField textFieldHGT;
    private JTextField textFieldNumSigaretteDie;
    private JTextField textFieldQuantitaAlcoolDie;
    private JTextField textFieldPortatoreDiProtesiSi;
    private JTextArea textAreaDiagnosiDIngresso;
    private JTextArea textAreaInterventiChirurgici;
    private JTextArea textAreaDignosiDiDimissione;
    private JTextArea textAreaAnamnesiFamiliare;
    private JTextArea textAreaAllergiaIntolleranzeAdAlimenti;
    private JTextArea textAreaAllergiaAdAltreSostanze;
    private JTextArea textAreaAllergiaNotaAFarmaci;
    private JTextArea textAreaAnamnesiPatologicaProssima;
    private JTextArea textAreaAssunzioneAnticoagulantiOrali;
    private JTextArea textAreaAssunzioneIpoglicemizzantiOrali;
    private JTextArea textAreaAssunzioneImmunosoppressori;
    private JTextArea textAreaSomministrazioneInsulina;
    private JTextArea textAreaFavismo;
    private JTextArea textAreaAssunzioneAntiiperestensivi;
    private JTextArea textAreaAssunzioneDiuretici;
    private JTextArea textAreaAssunzionePsicofarmaci;
    private JTextArea textAreaTiroide;
    private JTextArea textAreaFunzioniCognitive;
    private JTextArea textAreaCute;
    private JTextArea textAreaAltreEventualiAlterazioniCutanee;
    private JTextArea textAreaAlterazioniDelRespiro;
    private JPanel panel_Accettazione;
    private JPanel panelAccettazionePaziente;
    private JPanel panel_ValutazioneInizialeInfermieristica;
    private JPanel panel_ValutazioneClinicaIniziale;
    private JPanel panel_TerapiaDomiciliare;
    private JPanel panel_EsameObiettivo;
    private Object[][] dataRow;
    
    static {
        gruppoRegimeDiRicovero = new ButtonGroup();
        gruppoProvenienteDa = new ButtonGroup();
        gruppoTipologiaDimissione = new ButtonGroup();
        buttonGroup_1 = new ButtonGroup();
        gruppoScreeningDolore = new ButtonGroup();
        gruppoScalaDolore = new ButtonGroup();
        gruppoFumatore = new ButtonGroup();
        gruppoUsoDiAlcool = new ButtonGroup();
        gruppoIgienePersonale = new ButtonGroup();
        gruppoCaratteristicheDelSonno = new ButtonGroup();
        gruppoStatoEmotivo = new ButtonGroup();
        gruppoMovimento = new ButtonGroup();
        gruppoAlimentazione = new ButtonGroup();
        gruppoMinzione = new ButtonGroup();
        gruppoAlvo = new ButtonGroup();
        gruppoStomie = new ButtonGroup();
        gruppoIncontinenza = new ButtonGroup();
        gruppoAllergiaIntolleranzeAdAlimenti = new ButtonGroup();
        gruppoAllergiaAlLattice = new ButtonGroup();
        gruppoAllergiaAdAltreSostanze = new ButtonGroup();
        gruppoAllergiaNotaAFarmaci = new ButtonGroup();
        gruppoAssunzioneAnticoagulantiOrali = new ButtonGroup();
        gruppoAssunzioneImmunosoppressori = new ButtonGroup();
        gruppoAssunzioneIpoglicemizzantiOrali = new ButtonGroup();
        gruppoSomministrazioneInsulina = new ButtonGroup();
        gruppoFavismo = new ButtonGroup();
        gruppoAssunzioneAntiiperestensivi = new ButtonGroup();
        gruppoAssunzioneDiuretici = new ButtonGroup();
        gruppoPsicofarmaci = new ButtonGroup();
        gruppoTiroide = new ButtonGroup();
        gruppoCondizioniGenerali = new ButtonGroup();
        gruppoFunzioniCognitive = new ButtonGroup();
        gruppoSensorio = new ButtonGroup();
        gruppoCute = new ButtonGroup();
        gruppoAltreEventualiAlterazioniCutanee = new ButtonGroup();
        gruppoMucoseVisibili = new ButtonGroup();
        gruppoAlterazioniDelRespiro = new ButtonGroup();
        gruppoPortatoreDiProtesi = new ButtonGroup();
        gruppoAnamnesiFamiliare = new ButtonGroup();
        gruppoScreeningStatoNutrizionale = new ButtonGroup();
    }
    
    public FrameCartellaClinicaModel(final Paziente paziente) {
        this.cardLayout = new CardLayout();
        this.cardLayoutTextArea = new CardLayout();
        this.creaPannelloAccettazione(paziente);
        serializzaPannelloAccettazione(this.panel_Accettazione, paziente);
        this.creaPannelloValutazioneInizialeInfermieristica(paziente);
        serializzaPannelloValutazioneInizialeInfermieristica(this.panel_ValutazioneInizialeInfermieristica, paziente);
        this.creaPannelloValutazioneInizialeClinica(paziente);
        serializzaPannelloValutazioneInizialeClinica(this.panel_ValutazioneClinicaIniziale, paziente);
        this.creaPannelloTerapiaDomicialiare(paziente);
        serializzaPannelloTerapiaDomiciliare(this.panel_TerapiaDomiciliare, paziente);
        this.creaPanneloEsameObiettivo(paziente);
        serializzaPannelloEsameObiettivo(this.panel_EsameObiettivo, paziente);
        this.creaMatriceDiarioClinico(paziente);
        serializzaMatriceDiarioClinico(this.dataRow, paziente);
    }
    
    public static void serializzaMatriceDiarioClinico(final Object[][] dataR, final Paziente p1) {
        try {
            final FileOutputStream fileOut = new FileOutputStream(String.valueOf(ControlloOs.controlloOs()) + "Ospedale//" + p1.getTipoReparto().getNomeReparto() + "//" + p1.getCodFiscale() + "//MatriceDiarioClinico.txt");
            final ObjectOutputStream ois = new ObjectOutputStream(fileOut);
            ois.writeObject(dataR);
            ois.close();
            System.out.println("Matrice Serializzata");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public static void serializzaPannelloEsameObiettivo(final JPanel panel, final Paziente p1) {
        try {
            final FileOutputStream fileOut = new FileOutputStream(String.valueOf(ControlloOs.controlloOs()) + "Ospedale//" + p1.getTipoReparto().getNomeReparto() + "//" + p1.getCodFiscale() + "//PanelloEsameObiettivo.txt");
            final ObjectOutputStream ois = new ObjectOutputStream(fileOut);
            ois.writeObject(panel);
            ois.close();
            System.out.println("Esame serializzato");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public static void serializzaPannelloTerapiaDomiciliare(final JPanel panel, final Paziente p1) {
        try {
            final FileOutputStream fileOut = new FileOutputStream(String.valueOf(ControlloOs.controlloOs()) + "Ospedale//" + p1.getTipoReparto().getNomeReparto() + "//" + p1.getCodFiscale() + "//PannelloTerapiaDomiciliare.txt");
            final ObjectOutputStream ois = new ObjectOutputStream(fileOut);
            ois.writeObject(panel);
            ois.close();
            System.out.println("Terapia Serializzata");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public static void serializzaPannelloValutazioneInizialeClinica(final JPanel panel, final Paziente p1) {
        try {
            final FileOutputStream fileOut = new FileOutputStream(String.valueOf(ControlloOs.controlloOs()) + "Ospedale//" + p1.getTipoReparto().getNomeReparto() + "//" + p1.getCodFiscale() + "//PannelloValutazioneClinica.txt");
            final ObjectOutputStream ois = new ObjectOutputStream(fileOut);
            ois.writeObject(panel);
            ois.close();
            System.out.println("Clinica Serializzata");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public static void serializzaPannelloValutazioneInizialeInfermieristica(final JPanel panel, final Paziente p1) {
        try {
            final FileOutputStream fileOut = new FileOutputStream(String.valueOf(ControlloOs.controlloOs()) + "Ospedale//" + p1.getTipoReparto().getNomeReparto() + "//" + p1.getCodFiscale() + "//PannelloValutazioneInfermieristica.txt");
            final ObjectOutputStream ois = new ObjectOutputStream(fileOut);
            ois.writeObject(panel);
            ois.close();
            System.out.println("Infermieristica Serializzata");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public static void serializzaPannelloAccettazione(final JPanel panel, final Paziente p1) {
        try {
            final FileOutputStream fileOut = new FileOutputStream(String.valueOf(ControlloOs.controlloOs()) + "Ospedale//" + p1.getTipoReparto().getNomeReparto() + "//" + p1.getCodFiscale() + "//PannelloAccettazione.txt");
            final ObjectOutputStream ois = new ObjectOutputStream(fileOut);
            ois.writeObject(panel);
            ois.close();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public static void serializzaPannelloAccettazione(final JPanel panel, final Paziente p1, final boolean ePaziente) {
        try {
            final FileOutputStream fileOut1 = new FileOutputStream(String.valueOf(ControlloOs.controlloOs()) + "Ospedale//" + p1.getTipoReparto().getNomeReparto() + "//" + p1.getCodFiscale() + "//PannelloAccettazionePaziente.txt");
            final ObjectOutputStream ois1 = new ObjectOutputStream(fileOut1);
            ois1.writeObject(panel);
            ois1.close();
            System.out.println("Accettazione Serializzata");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void creaMatriceDiarioClinico(final Paziente p1) {
        this.dataRow = new Object[0][2];
    }
    
    private void creaPanneloEsameObiettivo(final Paziente p1) {
        (this.panel_EsameObiettivo = new JPanel()).setBackground(Color.WHITE);
        this.panel_EsameObiettivo.setLayout(new GridLayout(8, 3, 0, 0));
        final JLabel lblCondizioniGenerali = new JLabel(" Condizioni generali: ");
        lblCondizioniGenerali.setBackground(Color.WHITE);
        lblCondizioniGenerali.setFont(new Font("Tahoma", 1, 11));
        this.panel_EsameObiettivo.add(lblCondizioniGenerali);
        final JPanel panel_24 = new JPanel();
        panel_24.setBackground(Color.WHITE);
        this.panel_EsameObiettivo.add(panel_24);
        final JCheckBox chckbxBuone = new JCheckBox("Buone");
        FrameCartellaClinicaModel.gruppoCondizioniGenerali.add(chckbxBuone);
        chckbxBuone.setBackground(Color.WHITE);
        panel_24.add(chckbxBuone);
        final JCheckBox chckbxMediocri = new JCheckBox("Mediocri");
        FrameCartellaClinicaModel.gruppoCondizioniGenerali.add(chckbxMediocri);
        chckbxMediocri.setBackground(Color.WHITE);
        panel_24.add(chckbxMediocri);
        final JCheckBox chckbxScadenti = new JCheckBox("Scadenti");
        FrameCartellaClinicaModel.gruppoCondizioniGenerali.add(chckbxScadenti);
        chckbxScadenti.setBackground(Color.WHITE);
        panel_24.add(chckbxScadenti);
        final JCheckBox chckbxCritiche = new JCheckBox("Critiche");
        FrameCartellaClinicaModel.gruppoCondizioniGenerali.add(chckbxCritiche);
        chckbxCritiche.setBackground(Color.WHITE);
        panel_24.add(chckbxCritiche);
        final JPanel panel_25 = new JPanel();
        panel_25.setBackground(Color.WHITE);
        this.panel_EsameObiettivo.add(panel_25);
        panel_25.setLayout(new BoxLayout(panel_25, 0));
        final JLabel lblFunzioniCognitive = new JLabel(" Funzioni cognitive: ");
        lblFunzioniCognitive.setFont(new Font("Tahoma", 1, 11));
        this.panel_EsameObiettivo.add(lblFunzioniCognitive);
        final JPanel panel_26 = new JPanel();
        panel_26.setBackground(Color.WHITE);
        this.panel_EsameObiettivo.add(panel_26);
        final JCheckBox chckbxNonRilevabile_16 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoFunzioniCognitive.add(chckbxNonRilevabile_16);
        chckbxNonRilevabile_16.setBackground(Color.WHITE);
        panel_26.add(chckbxNonRilevabile_16);
        final JCheckBox chckbxConservate = new JCheckBox("Conservate");
        FrameCartellaClinicaModel.gruppoFunzioniCognitive.add(chckbxConservate);
        chckbxConservate.setBackground(Color.WHITE);
        panel_26.add(chckbxConservate);
        final JCheckBox chckbxAlterate = new JCheckBox("Alterate");
        FrameCartellaClinicaModel.gruppoFunzioniCognitive.add(chckbxAlterate);
        chckbxAlterate.setBackground(Color.WHITE);
        panel_26.add(chckbxAlterate);
        final JPanel panel_27 = new JPanel();
        this.panel_EsameObiettivo.add(panel_27);
        panel_27.setLayout(new BoxLayout(panel_27, 0));
        (this.textAreaFunzioniCognitive = new JTextArea()).setBorder(new LineBorder(Color.RED));
        final JScrollPane scrollPane_18 = new JScrollPane(this.textAreaFunzioniCognitive);
        panel_27.add(scrollPane_18);
        final JLabel lblSensorio = new JLabel(" Sensorio: ");
        lblSensorio.setFont(new Font("Tahoma", 1, 11));
        this.panel_EsameObiettivo.add(lblSensorio);
        final JPanel panel_28 = new JPanel();
        panel_28.setBackground(Color.WHITE);
        this.panel_EsameObiettivo.add(panel_28);
        final JCheckBox chckbxIntergro = new JCheckBox("Integro");
        FrameCartellaClinicaModel.gruppoSensorio.add(chckbxIntergro);
        chckbxIntergro.setBackground(Color.WHITE);
        panel_28.add(chckbxIntergro);
        final JCheckBox chckbxConfuso = new JCheckBox("Confuso");
        FrameCartellaClinicaModel.gruppoSensorio.add(chckbxConfuso);
        chckbxConfuso.setBackground(Color.WHITE);
        panel_28.add(chckbxConfuso);
        final JCheckBox chckbxSoporoso = new JCheckBox("Soporoso");
        FrameCartellaClinicaModel.gruppoSensorio.add(chckbxSoporoso);
        chckbxSoporoso.setBackground(Color.WHITE);
        panel_28.add(chckbxSoporoso);
        final JCheckBox chckbxComatoso = new JCheckBox("Comatoso");
        FrameCartellaClinicaModel.gruppoSensorio.add(chckbxComatoso);
        chckbxComatoso.setBackground(Color.WHITE);
        panel_28.add(chckbxComatoso);
        final JCheckBox chckbxAgitato = new JCheckBox("Agitato");
        FrameCartellaClinicaModel.gruppoSensorio.add(chckbxAgitato);
        chckbxAgitato.setBackground(Color.WHITE);
        panel_28.add(chckbxAgitato);
        final JPanel panel_29 = new JPanel();
        panel_29.setBackground(Color.WHITE);
        this.panel_EsameObiettivo.add(panel_29);
        panel_29.setLayout(new BoxLayout(panel_29, 0));
        final JLabel lblCute = new JLabel(" Cute: ");
        lblCute.setFont(new Font("Tahoma", 1, 11));
        this.panel_EsameObiettivo.add(lblCute);
        final JPanel panel_30 = new JPanel();
        panel_30.setBackground(Color.WHITE);
        this.panel_EsameObiettivo.add(panel_30);
        final JCheckBox chckbxRosea = new JCheckBox("Rosea");
        FrameCartellaClinicaModel.gruppoCute.add(chckbxRosea);
        chckbxRosea.setBackground(Color.WHITE);
        panel_30.add(chckbxRosea);
        final JCheckBox chckbxPallida = new JCheckBox("Pallida");
        FrameCartellaClinicaModel.gruppoCute.add(chckbxPallida);
        chckbxPallida.setBackground(Color.WHITE);
        panel_30.add(chckbxPallida);
        final JCheckBox chckbxSudata = new JCheckBox("Sudata");
        FrameCartellaClinicaModel.gruppoCute.add(chckbxSudata);
        chckbxSudata.setBackground(Color.WHITE);
        panel_30.add(chckbxSudata);
        final JCheckBox chckbxCianotica = new JCheckBox("Cianotica");
        FrameCartellaClinicaModel.gruppoCute.add(chckbxCianotica);
        chckbxCianotica.setBackground(Color.WHITE);
        panel_30.add(chckbxCianotica);
        final JCheckBox chckbxItterica = new JCheckBox("Itterica");
        FrameCartellaClinicaModel.gruppoCute.add(chckbxItterica);
        chckbxItterica.setBackground(Color.WHITE);
        panel_30.add(chckbxItterica);
        final JCheckBox chckbxEdematosa = new JCheckBox("Edematosa");
        FrameCartellaClinicaModel.gruppoCute.add(chckbxEdematosa);
        chckbxEdematosa.setBackground(Color.WHITE);
        panel_30.add(chckbxEdematosa);
        final JPanel panel_31 = new JPanel();
        panel_31.setBackground(Color.WHITE);
        this.panel_EsameObiettivo.add(panel_31);
        panel_31.setLayout(new BorderLayout(0, 0));
        (this.textAreaCute = new JTextArea()).setBorder(new LineBorder(Color.RED));
        final JScrollPane scrollPane_19 = new JScrollPane(this.textAreaCute);
        panel_31.add(scrollPane_19);
        final JLabel lblNewLabel_4 = new JLabel("                                    Sede: ");
        lblNewLabel_4.setFont(new Font("Tahoma", 1, 10));
        panel_31.add(lblNewLabel_4, "North");
        final JLabel lblAltreEventualiAlterazioni = new JLabel(" Altre eventuali alterazioni cutanee: ");
        lblAltreEventualiAlterazioni.setFont(new Font("Tahoma", 1, 11));
        this.panel_EsameObiettivo.add(lblAltreEventualiAlterazioni);
        final JPanel panel_32 = new JPanel();
        panel_32.setBackground(Color.WHITE);
        this.panel_EsameObiettivo.add(panel_32);
        panel_32.setLayout(new FlowLayout(1, 5, 5));
        final JCheckBox chckbxNo_19 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoAltreEventualiAlterazioniCutanee.add(chckbxNo_19);
        chckbxNo_19.setBackground(Color.WHITE);
        panel_32.add(chckbxNo_19);
        final JCheckBox chckbxSi_18 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoAltreEventualiAlterazioniCutanee.add(chckbxSi_18);
        chckbxSi_18.setBackground(Color.WHITE);
        panel_32.add(chckbxSi_18);
        final JPanel panel_33 = new JPanel();
        this.panel_EsameObiettivo.add(panel_33);
        panel_33.setLayout(new BoxLayout(panel_33, 0));
        (this.textAreaAltreEventualiAlterazioniCutanee = new JTextArea()).setBorder(new LineBorder(Color.RED));
        final JScrollPane scrollPane_20 = new JScrollPane(this.textAreaAltreEventualiAlterazioniCutanee);
        panel_33.add(scrollPane_20);
        final JLabel lblMucoseVisibili = new JLabel(" Mucose visibili: ");
        lblMucoseVisibili.setFont(new Font("Tahoma", 1, 11));
        this.panel_EsameObiettivo.add(lblMucoseVisibili);
        final JPanel panel_34 = new JPanel();
        panel_34.setBackground(Color.WHITE);
        this.panel_EsameObiettivo.add(panel_34);
        final JCheckBox chckbxRosee = new JCheckBox("Rosee");
        FrameCartellaClinicaModel.gruppoMucoseVisibili.add(chckbxRosee);
        chckbxRosee.setBackground(Color.WHITE);
        panel_34.add(chckbxRosee);
        final JCheckBox chckbxPallide = new JCheckBox("Pallide");
        FrameCartellaClinicaModel.gruppoMucoseVisibili.add(chckbxPallide);
        chckbxPallide.setBackground(Color.WHITE);
        panel_34.add(chckbxPallide);
        final JCheckBox chckbxUmide = new JCheckBox("Umide");
        FrameCartellaClinicaModel.gruppoMucoseVisibili.add(chckbxUmide);
        chckbxUmide.setBackground(Color.WHITE);
        panel_34.add(chckbxUmide);
        final JCheckBox chckbxCianotiche = new JCheckBox("Cianotiche");
        FrameCartellaClinicaModel.gruppoMucoseVisibili.add(chckbxCianotiche);
        chckbxCianotiche.setBackground(Color.WHITE);
        panel_34.add(chckbxCianotiche);
        final JCheckBox chckbxItteriche = new JCheckBox("Itteriche");
        FrameCartellaClinicaModel.gruppoMucoseVisibili.add(chckbxItteriche);
        chckbxItteriche.setBackground(Color.WHITE);
        panel_34.add(chckbxItteriche);
        final JPanel panel_35 = new JPanel();
        panel_35.setBackground(Color.WHITE);
        this.panel_EsameObiettivo.add(panel_35);
        panel_35.setLayout(new BoxLayout(panel_35, 0));
        final JLabel lblAlterazioniDelRespiro = new JLabel(" Alterazioni del respiro: ");
        lblAlterazioniDelRespiro.setFont(new Font("Tahoma", 1, 11));
        this.panel_EsameObiettivo.add(lblAlterazioniDelRespiro);
        final JPanel panel_36 = new JPanel();
        panel_36.setBackground(Color.WHITE);
        this.panel_EsameObiettivo.add(panel_36);
        final JCheckBox chckbxNo_20 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoAlterazioniDelRespiro.add(chckbxNo_20);
        chckbxNo_20.setBackground(Color.WHITE);
        panel_36.add(chckbxNo_20);
        final JCheckBox chckbxSi_19 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoAlterazioniDelRespiro.add(chckbxSi_19);
        chckbxSi_19.setBackground(Color.WHITE);
        panel_36.add(chckbxSi_19);
        final JPanel panel_37 = new JPanel();
        this.panel_EsameObiettivo.add(panel_37);
        panel_37.setLayout(new BoxLayout(panel_37, 0));
        (this.textAreaAlterazioniDelRespiro = new JTextArea()).setBorder(new LineBorder(Color.RED));
        final JScrollPane scrollPane_21 = new JScrollPane(this.textAreaAlterazioniDelRespiro);
        panel_37.add(scrollPane_21);
        final JLabel lblScreeningStatoNutrizionale = new JLabel("Screening stato nutrizionale: ");
        lblScreeningStatoNutrizionale.setFont(new Font("Tahoma", 1, 11));
        this.panel_EsameObiettivo.add(lblScreeningStatoNutrizionale);
        final JPanel panel_38 = new JPanel();
        panel_38.setBackground(Color.WHITE);
        this.panel_EsameObiettivo.add(panel_38);
        final JCheckBox chckbxNormonutrito = new JCheckBox("Normonutrito");
        FrameCartellaClinicaModel.gruppoScreeningStatoNutrizionale.add(chckbxNormonutrito);
        chckbxNormonutrito.setBackground(Color.WHITE);
        panel_38.add(chckbxNormonutrito);
        final JCheckBox chckbxSottonutrito = new JCheckBox("Sottonutrito");
        FrameCartellaClinicaModel.gruppoScreeningStatoNutrizionale.add(chckbxSottonutrito);
        chckbxSottonutrito.setBackground(Color.WHITE);
        panel_38.add(chckbxSottonutrito);
        final JCheckBox chckbxSovranutrito = new JCheckBox("Sovranutrito");
        FrameCartellaClinicaModel.gruppoScreeningStatoNutrizionale.add(chckbxSovranutrito);
        chckbxSovranutrito.setBackground(Color.WHITE);
        panel_38.add(chckbxSovranutrito);
        final JPanel panel_39 = new JPanel();
        panel_39.setBackground(Color.WHITE);
        this.panel_EsameObiettivo.add(panel_39);
        panel_39.setLayout(new BoxLayout(panel_39, 0));
    }
    
    private void creaPannelloTerapiaDomicialiare(final Paziente p1) {
        (this.panel_TerapiaDomiciliare = new JPanel()).setLayout(new BoxLayout(this.panel_TerapiaDomiciliare, 1));
        final JPanel panel_25 = new JPanel();
        panel_25.setBackground(Color.WHITE);
        this.panel_TerapiaDomiciliare.add(panel_25);
        panel_25.setLayout(new GridLayout(0, 3, 0, 0));
        final JLabel label_3 = new JLabel(" Assunzione anticoagulanti orali: ");
        label_3.setFont(new Font("Tahoma", 1, 11));
        panel_25.add(label_3);
        final JPanel panel_26 = new JPanel();
        panel_26.setBackground(Color.WHITE);
        panel_25.add(panel_26);
        panel_26.setLayout(new FlowLayout(1, 5, 5));
        final JCheckBox chckbxNonRilevabile_7 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoAssunzioneAnticoagulantiOrali.add(chckbxNonRilevabile_7);
        chckbxNonRilevabile_7.setBackground(Color.WHITE);
        panel_26.add(chckbxNonRilevabile_7);
        final JCheckBox chckbxNo_11 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoAssunzioneAnticoagulantiOrali.add(chckbxNo_11);
        chckbxNo_11.setBackground(Color.WHITE);
        panel_26.add(chckbxNo_11);
        final JCheckBox chckbxNonRicorda_4 = new JCheckBox("NON RICORDA");
        FrameCartellaClinicaModel.gruppoAssunzioneAnticoagulantiOrali.add(chckbxNonRicorda_4);
        chckbxNonRicorda_4.setBackground(Color.WHITE);
        panel_26.add(chckbxNonRicorda_4);
        final JCheckBox chckbxSi_9 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoAssunzioneAnticoagulantiOrali.add(chckbxSi_9);
        chckbxSi_9.setBackground(Color.WHITE);
        panel_26.add(chckbxSi_9);
        final JPanel panel_27 = new JPanel();
        panel_25.add(panel_27);
        panel_27.setLayout(new BoxLayout(panel_27, 0));
        (this.textAreaAssunzioneAnticoagulantiOrali = new JTextArea()).setBorder(new LineBorder(new Color(0, 0, 0)));
        final JScrollPane scrollPane_8 = new JScrollPane(this.textAreaAssunzioneAnticoagulantiOrali);
        panel_27.add(scrollPane_8);
        final JLabel label_4 = new JLabel(" Assunzione immunosoppressori: ");
        label_4.setFont(new Font("Tahoma", 1, 11));
        panel_25.add(label_4);
        final JPanel panel_28 = new JPanel();
        panel_28.setBackground(Color.WHITE);
        panel_25.add(panel_28);
        panel_28.setLayout(new FlowLayout(1, 5, 5));
        final JCheckBox chckbxNonRilevabile_8 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoAssunzioneImmunosoppressori.add(chckbxNonRilevabile_8);
        chckbxNonRilevabile_8.setBackground(Color.WHITE);
        panel_28.add(chckbxNonRilevabile_8);
        final JCheckBox chckbxNo_12 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoAssunzioneImmunosoppressori.add(chckbxNo_12);
        chckbxNo_12.setBackground(Color.WHITE);
        panel_28.add(chckbxNo_12);
        final JCheckBox chckbxNonRicorda_5 = new JCheckBox("NON  RICORDA");
        FrameCartellaClinicaModel.gruppoAssunzioneImmunosoppressori.add(chckbxNonRicorda_5);
        chckbxNonRicorda_5.setBackground(Color.WHITE);
        panel_28.add(chckbxNonRicorda_5);
        final JCheckBox chckbxSi_10 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoAssunzioneImmunosoppressori.add(chckbxSi_10);
        chckbxSi_10.setBackground(Color.WHITE);
        panel_28.add(chckbxSi_10);
        final JPanel panel_29 = new JPanel();
        panel_25.add(panel_29);
        panel_29.setLayout(new BoxLayout(panel_29, 0));
        (this.textAreaAssunzioneImmunosoppressori = new JTextArea()).setBorder(new LineBorder(new Color(0, 0, 0)));
        final JScrollPane scrollPane_9 = new JScrollPane(this.textAreaAssunzioneImmunosoppressori);
        panel_29.add(scrollPane_9);
        final JLabel label_5 = new JLabel(" Assunzione ipoglicemizzanti orali: ");
        label_5.setBackground(Color.WHITE);
        label_5.setFont(new Font("Tahoma", 1, 11));
        panel_25.add(label_5);
        final JPanel panel_30 = new JPanel();
        panel_30.setBackground(Color.WHITE);
        panel_25.add(panel_30);
        final JCheckBox chckbxNonRilevabile_9 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoAssunzioneIpoglicemizzantiOrali.add(chckbxNonRilevabile_9);
        chckbxNonRilevabile_9.setBackground(Color.WHITE);
        panel_30.add(chckbxNonRilevabile_9);
        final JCheckBox chckbxNo_13 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoAssunzioneIpoglicemizzantiOrali.add(chckbxNo_13);
        chckbxNo_13.setBackground(Color.WHITE);
        panel_30.add(chckbxNo_13);
        final JCheckBox chckbxNonRicordo = new JCheckBox("NON RICORDA");
        FrameCartellaClinicaModel.gruppoAssunzioneIpoglicemizzantiOrali.add(chckbxNonRicordo);
        chckbxNonRicordo.setBackground(Color.WHITE);
        panel_30.add(chckbxNonRicordo);
        final JCheckBox chckbxSi_11 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoAssunzioneIpoglicemizzantiOrali.add(chckbxSi_11);
        chckbxSi_11.setBackground(Color.WHITE);
        panel_30.add(chckbxSi_11);
        final JPanel panel_31 = new JPanel();
        panel_25.add(panel_31);
        panel_31.setLayout(new BoxLayout(panel_31, 0));
        (this.textAreaAssunzioneIpoglicemizzantiOrali = new JTextArea()).setBorder(new LineBorder(new Color(0, 0, 0)));
        final JScrollPane scrollPane_10 = new JScrollPane(this.textAreaAssunzioneIpoglicemizzantiOrali);
        panel_31.add(scrollPane_10);
        final JLabel label_6 = new JLabel(" Somministrazione insulina: ");
        label_6.setFont(new Font("Tahoma", 1, 11));
        panel_25.add(label_6);
        final JPanel panel_32 = new JPanel();
        panel_32.setBackground(Color.WHITE);
        panel_25.add(panel_32);
        final JCheckBox chckbxNonRilevabile_10 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoSomministrazioneInsulina.add(chckbxNonRilevabile_10);
        chckbxNonRilevabile_10.setBackground(Color.WHITE);
        panel_32.add(chckbxNonRilevabile_10);
        final JCheckBox chckbxNo_14 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoSomministrazioneInsulina.add(chckbxNo_14);
        chckbxNo_14.setBackground(Color.WHITE);
        panel_32.add(chckbxNo_14);
        final JCheckBox chckbxNonRicorda_6 = new JCheckBox("NON RICORDA");
        FrameCartellaClinicaModel.gruppoSomministrazioneInsulina.add(chckbxNonRicorda_6);
        chckbxNonRicorda_6.setBackground(Color.WHITE);
        panel_32.add(chckbxNonRicorda_6);
        final JCheckBox chckbxSi_12 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoSomministrazioneInsulina.add(chckbxSi_12);
        chckbxSi_12.setBackground(Color.WHITE);
        panel_32.add(chckbxSi_12);
        final JPanel panel_33 = new JPanel();
        panel_25.add(panel_33);
        panel_33.setLayout(new BoxLayout(panel_33, 0));
        (this.textAreaSomministrazioneInsulina = new JTextArea()).setBorder(new LineBorder(new Color(0, 0, 0)));
        final JScrollPane scrollPane_11 = new JScrollPane(this.textAreaSomministrazioneInsulina);
        panel_33.add(scrollPane_11);
        final JLabel label_7 = new JLabel(" Favismo: ");
        label_7.setFont(new Font("Tahoma", 1, 11));
        panel_25.add(label_7);
        final JPanel panel_34 = new JPanel();
        panel_34.setBackground(Color.WHITE);
        panel_25.add(panel_34);
        final JCheckBox chckbxNonRilevabile_11 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoFavismo.add(chckbxNonRilevabile_11);
        chckbxNonRilevabile_11.setBackground(Color.WHITE);
        panel_34.add(chckbxNonRilevabile_11);
        final JCheckBox chckbxNo_15 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoFavismo.add(chckbxNo_15);
        chckbxNo_15.setBackground(Color.WHITE);
        panel_34.add(chckbxNo_15);
        final JCheckBox chckbxNonRicorda_7 = new JCheckBox("NON RICORDA");
        FrameCartellaClinicaModel.gruppoFavismo.add(chckbxNonRicorda_7);
        chckbxNonRicorda_7.setBackground(Color.WHITE);
        panel_34.add(chckbxNonRicorda_7);
        final JCheckBox chckbxSi_13 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoFavismo.add(chckbxSi_13);
        chckbxSi_13.setBackground(Color.WHITE);
        panel_34.add(chckbxSi_13);
        final JPanel panel_35 = new JPanel();
        panel_25.add(panel_35);
        panel_35.setLayout(new BoxLayout(panel_35, 0));
        (this.textAreaFavismo = new JTextArea()).setBorder(new LineBorder(new Color(0, 0, 0)));
        final JScrollPane scrollPane_12 = new JScrollPane(this.textAreaFavismo);
        panel_35.add(scrollPane_12);
        final JLabel label_8 = new JLabel(" Assunzione antiiperestensivi: ");
        label_8.setFont(new Font("Tahoma", 1, 11));
        panel_25.add(label_8);
        final JPanel panel_36 = new JPanel();
        panel_36.setBackground(Color.WHITE);
        panel_25.add(panel_36);
        final JCheckBox chckbxNonRilevabile_12 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoAssunzioneAntiiperestensivi.add(chckbxNonRilevabile_12);
        chckbxNonRilevabile_12.setBackground(Color.WHITE);
        panel_36.add(chckbxNonRilevabile_12);
        final JCheckBox chckbxNo_16 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoAssunzioneAntiiperestensivi.add(chckbxNo_16);
        chckbxNo_16.setBackground(Color.WHITE);
        panel_36.add(chckbxNo_16);
        final JCheckBox chckbxNonRicorda_8 = new JCheckBox("NON RICORDA");
        FrameCartellaClinicaModel.gruppoAssunzioneAntiiperestensivi.add(chckbxNonRicorda_8);
        chckbxNonRicorda_8.setBackground(Color.WHITE);
        panel_36.add(chckbxNonRicorda_8);
        final JCheckBox chckbxSi_14 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoAssunzioneAntiiperestensivi.add(chckbxSi_14);
        chckbxSi_14.setBackground(Color.WHITE);
        panel_36.add(chckbxSi_14);
        final JPanel panel_37 = new JPanel();
        panel_25.add(panel_37);
        panel_37.setLayout(new BoxLayout(panel_37, 0));
        (this.textAreaAssunzioneAntiiperestensivi = new JTextArea()).setBorder(new LineBorder(new Color(0, 0, 0)));
        final JScrollPane scrollPane_13 = new JScrollPane(this.textAreaAssunzioneAntiiperestensivi);
        panel_37.add(scrollPane_13);
        final JLabel label_9 = new JLabel(" Assunzione diuretici: ");
        label_9.setFont(new Font("Tahoma", 1, 11));
        panel_25.add(label_9);
        final JPanel panel_38 = new JPanel();
        panel_38.setBackground(Color.WHITE);
        panel_25.add(panel_38);
        final JCheckBox chckbxNonRilevabile_13 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoAssunzioneDiuretici.add(chckbxNonRilevabile_13);
        chckbxNonRilevabile_13.setBackground(Color.WHITE);
        panel_38.add(chckbxNonRilevabile_13);
        final JCheckBox chckbxN = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoAssunzioneDiuretici.add(chckbxN);
        chckbxN.setBackground(Color.WHITE);
        panel_38.add(chckbxN);
        final JCheckBox chckbxNonRicorda_9 = new JCheckBox("NON RICORDA");
        FrameCartellaClinicaModel.gruppoAssunzioneDiuretici.add(chckbxNonRicorda_9);
        chckbxNonRicorda_9.setBackground(Color.WHITE);
        panel_38.add(chckbxNonRicorda_9);
        final JCheckBox chckbxSi_15 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoAssunzioneDiuretici.add(chckbxSi_15);
        chckbxSi_15.setBackground(Color.WHITE);
        panel_38.add(chckbxSi_15);
        final JPanel panel_39 = new JPanel();
        panel_25.add(panel_39);
        panel_39.setLayout(new BoxLayout(panel_39, 0));
        (this.textAreaAssunzioneDiuretici = new JTextArea()).setBorder(new LineBorder(new Color(0, 0, 0)));
        final JScrollPane scrollPane_14 = new JScrollPane(this.textAreaAssunzioneDiuretici);
        panel_39.add(scrollPane_14);
        final JLabel label_10 = new JLabel(" Assunzione psicofarmaci: ");
        label_10.setFont(new Font("Tahoma", 1, 11));
        panel_25.add(label_10);
        final JPanel panel_40 = new JPanel();
        panel_40.setBackground(Color.WHITE);
        panel_25.add(panel_40);
        final JCheckBox chckbxNonRilevabile_14 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoPsicofarmaci.add(chckbxNonRilevabile_14);
        chckbxNonRilevabile_14.setBackground(Color.WHITE);
        panel_40.add(chckbxNonRilevabile_14);
        final JCheckBox chckbxNo_17 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoPsicofarmaci.add(chckbxNo_17);
        chckbxNo_17.setBackground(Color.WHITE);
        panel_40.add(chckbxNo_17);
        final JCheckBox chckbxNonRicorda_10 = new JCheckBox("NON RICORDA");
        FrameCartellaClinicaModel.gruppoPsicofarmaci.add(chckbxNonRicorda_10);
        chckbxNonRicorda_10.setBackground(Color.WHITE);
        panel_40.add(chckbxNonRicorda_10);
        final JCheckBox chckbxSi_16 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoPsicofarmaci.add(chckbxSi_16);
        chckbxSi_16.setBackground(Color.WHITE);
        panel_40.add(chckbxSi_16);
        final JPanel panel_41 = new JPanel();
        panel_25.add(panel_41);
        panel_41.setLayout(new BoxLayout(panel_41, 0));
        (this.textAreaAssunzionePsicofarmaci = new JTextArea()).setBorder(new LineBorder(new Color(0, 0, 0)));
        final JScrollPane scrollPane_15 = new JScrollPane(this.textAreaAssunzionePsicofarmaci);
        panel_41.add(scrollPane_15);
        final JLabel label_11 = new JLabel(" Tiroide: ");
        label_11.setFont(new Font("Tahoma", 1, 11));
        panel_25.add(label_11);
        final JPanel panel_42 = new JPanel();
        panel_42.setBackground(Color.WHITE);
        panel_25.add(panel_42);
        final JCheckBox chckbxNonRilevabile_15 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoTiroide.add(chckbxNonRilevabile_15);
        chckbxNonRilevabile_15.setBackground(Color.WHITE);
        panel_42.add(chckbxNonRilevabile_15);
        final JCheckBox chckbxNo_18 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoTiroide.add(chckbxNo_18);
        chckbxNo_18.setBackground(Color.WHITE);
        panel_42.add(chckbxNo_18);
        final JCheckBox chckbxNonRicorda_11 = new JCheckBox("NON RICORDA");
        FrameCartellaClinicaModel.gruppoTiroide.add(chckbxNonRicorda_11);
        chckbxNonRicorda_11.setBackground(Color.WHITE);
        panel_42.add(chckbxNonRicorda_11);
        final JCheckBox chckbxSi_17 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoTiroide.add(chckbxSi_17);
        chckbxSi_17.setBackground(Color.WHITE);
        panel_42.add(chckbxSi_17);
        final JPanel panel_43 = new JPanel();
        panel_25.add(panel_43);
        panel_43.setLayout(new BoxLayout(panel_43, 0));
        (this.textAreaTiroide = new JTextArea()).setBorder(new LineBorder(new Color(0, 0, 0)));
        final JScrollPane scrollPane_16 = new JScrollPane(this.textAreaTiroide);
        panel_43.add(scrollPane_16);
    }
    
    private void creaPannelloValutazioneInizialeClinica(final Paziente p1) {
        (this.panel_ValutazioneClinicaIniziale = new JPanel()).setBackground(Color.WHITE);
        this.panel_ValutazioneClinicaIniziale.setLayout(new BoxLayout(this.panel_ValutazioneClinicaIniziale, 1));
        final JPanel panel_AnamnesiFamiliare = new JPanel();
        panel_AnamnesiFamiliare.setBackground(Color.WHITE);
        this.panel_ValutazioneClinicaIniziale.add(panel_AnamnesiFamiliare);
        final JLabel lblAnamnesiFamiliare = new JLabel("ANAMNESI FAMILIARE");
        lblAnamnesiFamiliare.setFont(new Font("Tahoma", 1, 11));
        panel_AnamnesiFamiliare.add(lblAnamnesiFamiliare);
        final JLabel lblDegnaDiNota = new JLabel(" degna di nota: ");
        panel_AnamnesiFamiliare.add(lblDegnaDiNota);
        final JCheckBox chckbxNo_3 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoAnamnesiFamiliare.add(chckbxNo_3);
        chckbxNo_3.setBackground(Color.WHITE);
        panel_AnamnesiFamiliare.add(chckbxNo_3);
        final JCheckBox chckbxSi_3 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoAnamnesiFamiliare.add(chckbxSi_3);
        chckbxSi_3.setBackground(Color.WHITE);
        panel_AnamnesiFamiliare.add(chckbxSi_3);
        final JPanel panel_AreaAnamnesiFamiliare = new JPanel();
        panel_AreaAnamnesiFamiliare.setBackground(Color.WHITE);
        this.panel_ValutazioneClinicaIniziale.add(panel_AreaAnamnesiFamiliare);
        panel_AreaAnamnesiFamiliare.setLayout(new BoxLayout(panel_AreaAnamnesiFamiliare, 0));
        (this.textAreaAnamnesiFamiliare = new JTextArea()).setBorder(new LineBorder(new Color(0, 0, 0)));
        final JScrollPane scrollPane_2 = new JScrollPane(this.textAreaAnamnesiFamiliare);
        panel_AreaAnamnesiFamiliare.add(scrollPane_2);
        final Component verticalStrut_1 = Box.createVerticalStrut(20);
        this.panel_ValutazioneClinicaIniziale.add(verticalStrut_1);
        final JPanel panel_AnamnesiFisiologica = new JPanel();
        panel_AnamnesiFisiologica.setBackground(Color.WHITE);
        this.panel_ValutazioneClinicaIniziale.add(panel_AnamnesiFisiologica);
        final JLabel lblAnamnesiPersonaleFamiliare = new JLabel("ANAMNESI PERSONALE FISIOLOGICA");
        lblAnamnesiPersonaleFamiliare.setBackground(Color.WHITE);
        lblAnamnesiPersonaleFamiliare.setFont(new Font("Tahoma", 1, 11));
        panel_AnamnesiFisiologica.add(lblAnamnesiPersonaleFamiliare);
        final JPanel panel_Fisilogica = new JPanel();
        panel_Fisilogica.setBackground(Color.WHITE);
        this.panel_ValutazioneClinicaIniziale.add(panel_Fisilogica);
        panel_Fisilogica.setLayout(new GridLayout(4, 3, 0, 0));
        final JLabel lblMinzione = new JLabel(" Minzione: ");
        lblMinzione.setFont(new Font("Tahoma", 1, 11));
        panel_Fisilogica.add(lblMinzione);
        final Component horizontalStrut_15 = Box.createHorizontalStrut(20);
        panel_Fisilogica.add(horizontalStrut_15);
        final JPanel panel_Minzione = new JPanel();
        panel_Minzione.setBackground(Color.WHITE);
        panel_Fisilogica.add(panel_Minzione);
        panel_Minzione.setLayout(new FlowLayout(1, 5, 5));
        final JCheckBox chckbxNonRilevabile_1 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoMinzione.add(chckbxNonRilevabile_1);
        chckbxNonRilevabile_1.setBackground(Color.WHITE);
        panel_Minzione.add(chckbxNonRilevabile_1);
        final JCheckBox chckbxRegolare_1 = new JCheckBox("regolare");
        FrameCartellaClinicaModel.gruppoMinzione.add(chckbxRegolare_1);
        chckbxRegolare_1.setBackground(Color.WHITE);
        panel_Minzione.add(chckbxRegolare_1);
        final JCheckBox chckbxAlterata = new JCheckBox("alterata");
        FrameCartellaClinicaModel.gruppoMinzione.add(chckbxAlterata);
        chckbxAlterata.setBackground(Color.WHITE);
        panel_Minzione.add(chckbxAlterata);
        final JLabel lblAlvo = new JLabel(" Alvo: ");
        lblAlvo.setFont(new Font("Tahoma", 1, 11));
        panel_Fisilogica.add(lblAlvo);
        final Component horizontalStrut_16 = Box.createHorizontalStrut(20);
        panel_Fisilogica.add(horizontalStrut_16);
        final JPanel panel_Alvo = new JPanel();
        panel_Alvo.setBackground(Color.WHITE);
        panel_Fisilogica.add(panel_Alvo);
        final JCheckBox chckbxNonRilevabile_2 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoAlvo.add(chckbxNonRilevabile_2);
        chckbxNonRilevabile_2.setBackground(Color.WHITE);
        panel_Alvo.add(chckbxNonRilevabile_2);
        final JCheckBox chckbxRegolare_2 = new JCheckBox("regolare");
        FrameCartellaClinicaModel.gruppoAlvo.add(chckbxRegolare_2);
        chckbxRegolare_2.setBackground(Color.WHITE);
        panel_Alvo.add(chckbxRegolare_2);
        final JCheckBox chckbxAlterato = new JCheckBox("alterato");
        FrameCartellaClinicaModel.gruppoAlvo.add(chckbxAlterato);
        chckbxAlterato.setBackground(Color.WHITE);
        panel_Alvo.add(chckbxAlterato);
        final JLabel lblStomie = new JLabel(" Stomie: ");
        lblStomie.setFont(new Font("Tahoma", 1, 11));
        panel_Fisilogica.add(lblStomie);
        final Component horizontalStrut_17 = Box.createHorizontalStrut(20);
        panel_Fisilogica.add(horizontalStrut_17);
        final JPanel panel_Stomie = new JPanel();
        panel_Stomie.setBackground(Color.WHITE);
        panel_Fisilogica.add(panel_Stomie);
        final JCheckBox chckbxNo_4 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoStomie.add(chckbxNo_4);
        chckbxNo_4.setBackground(Color.WHITE);
        panel_Stomie.add(chckbxNo_4);
        final JCheckBox chckbxSi_4 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoStomie.add(chckbxSi_4);
        chckbxSi_4.setBackground(Color.WHITE);
        panel_Stomie.add(chckbxSi_4);
        final JLabel lblIncontinenza = new JLabel(" Incontinenza: ");
        lblIncontinenza.setFont(new Font("Tahoma", 1, 11));
        panel_Fisilogica.add(lblIncontinenza);
        final Component horizontalStrut_18 = Box.createHorizontalStrut(20);
        panel_Fisilogica.add(horizontalStrut_18);
        final JPanel panel_Incontinenza = new JPanel();
        panel_Incontinenza.setBackground(Color.WHITE);
        panel_Fisilogica.add(panel_Incontinenza);
        final JCheckBox chckbxNo_5 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoIncontinenza.add(chckbxNo_5);
        chckbxNo_5.setBackground(Color.WHITE);
        panel_Incontinenza.add(chckbxNo_5);
        final JCheckBox chckbxSi_5 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoIncontinenza.add(chckbxSi_5);
        chckbxSi_5.setBackground(Color.WHITE);
        panel_Incontinenza.add(chckbxSi_5);
        final Component verticalStrut_2 = Box.createVerticalStrut(20);
        this.panel_ValutazioneClinicaIniziale.add(verticalStrut_2);
        final JPanel panel_AnamnesiRemota = new JPanel();
        panel_AnamnesiRemota.setBackground(Color.WHITE);
        this.panel_ValutazioneClinicaIniziale.add(panel_AnamnesiRemota);
        final JLabel lblAnamnesiPatologicaRemota = new JLabel("ANAMNESI PATOLOGICA REMOTA");
        lblAnamnesiPatologicaRemota.setFont(new Font("Tahoma", 1, 11));
        lblAnamnesiPatologicaRemota.setBackground(Color.WHITE);
        panel_AnamnesiRemota.add(lblAnamnesiPatologicaRemota);
        final JPanel panel_Remota = new JPanel();
        panel_Remota.setBackground(Color.WHITE);
        this.panel_ValutazioneClinicaIniziale.add(panel_Remota);
        panel_Remota.setLayout(new GridLayout(0, 4, 0, 0));
        final JLabel lblAllergiaIntolleranzeAd = new JLabel(" Allergia intolleranze ad alimenti: ");
        lblAllergiaIntolleranzeAd.setFont(new Font("Tahoma", 1, 11));
        panel_Remota.add(lblAllergiaIntolleranzeAd);
        final JPanel panel_12 = new JPanel();
        panel_12.setBackground(Color.WHITE);
        panel_Remota.add(panel_12);
        panel_12.setLayout(new BoxLayout(panel_12, 0));
        final JCheckBox chckbxNonRilevabile_3 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoAllergiaIntolleranzeAdAlimenti.add(chckbxNonRilevabile_3);
        chckbxNonRilevabile_3.setBackground(Color.WHITE);
        panel_12.add(chckbxNonRilevabile_3);
        final JCheckBox chckbxNonRicorda = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoAllergiaIntolleranzeAdAlimenti.add(chckbxNonRicorda);
        chckbxNonRicorda.setBackground(Color.WHITE);
        panel_12.add(chckbxNonRicorda);
        final JPanel panel_13 = new JPanel();
        panel_13.setBackground(Color.WHITE);
        panel_Remota.add(panel_13);
        panel_13.setLayout(new BoxLayout(panel_13, 0));
        final JCheckBox chckbxNo_6 = new JCheckBox("NON RICORDA");
        FrameCartellaClinicaModel.gruppoAllergiaIntolleranzeAdAlimenti.add(chckbxNo_6);
        chckbxNo_6.setBackground(Color.WHITE);
        panel_13.add(chckbxNo_6);
        final JCheckBox chckbxSi_6 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoAllergiaIntolleranzeAdAlimenti.add(chckbxSi_6);
        chckbxSi_6.setBackground(Color.WHITE);
        panel_13.add(chckbxSi_6);
        final JPanel panel_14 = new JPanel();
        panel_14.setBackground(Color.WHITE);
        panel_Remota.add(panel_14);
        panel_14.setLayout(new BoxLayout(panel_14, 0));
        this.textAreaAllergiaIntolleranzeAdAlimenti = new JTextArea();
        final JScrollPane scrollPane_3 = new JScrollPane(this.textAreaAllergiaIntolleranzeAdAlimenti);
        panel_14.add(scrollPane_3);
        final JLabel lblAllegieAlLattice = new JLabel(" Allergia al lattice: ");
        lblAllegieAlLattice.setFont(new Font("Tahoma", 1, 11));
        lblAllegieAlLattice.setBackground(Color.WHITE);
        panel_Remota.add(lblAllegieAlLattice);
        final JPanel panel_15 = new JPanel();
        panel_15.setBackground(Color.WHITE);
        panel_Remota.add(panel_15);
        panel_15.setLayout(new BoxLayout(panel_15, 0));
        final JCheckBox chckbxNonRilevabile_4 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoAllergiaAlLattice.add(chckbxNonRilevabile_4);
        chckbxNonRilevabile_4.setBackground(Color.WHITE);
        panel_15.add(chckbxNonRilevabile_4);
        final JCheckBox chckbxNo_7 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoAllergiaAlLattice.add(chckbxNo_7);
        chckbxNo_7.setBackground(Color.WHITE);
        panel_15.add(chckbxNo_7);
        final JPanel panel_16 = new JPanel();
        panel_16.setBackground(Color.WHITE);
        panel_Remota.add(panel_16);
        panel_16.setLayout(new BoxLayout(panel_16, 0));
        final JCheckBox chckbxNonRicorda_1 = new JCheckBox("NON RICORDA");
        FrameCartellaClinicaModel.gruppoAllergiaAlLattice.add(chckbxNonRicorda_1);
        chckbxNonRicorda_1.setBackground(Color.WHITE);
        panel_16.add(chckbxNonRicorda_1);
        final JCheckBox chckbxSi_7 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoAllergiaAlLattice.add(chckbxSi_7);
        chckbxSi_7.setBackground(Color.WHITE);
        panel_16.add(chckbxSi_7);
        final Component horizontalStrut_19 = Box.createHorizontalStrut(20);
        panel_Remota.add(horizontalStrut_19);
        final JLabel lblAllergieAdAltre = new JLabel(" Allergia ad altre sostanze: ");
        lblAllergieAdAltre.setFont(new Font("Tahoma", 1, 11));
        panel_Remota.add(lblAllergieAdAltre);
        final JPanel panel_17 = new JPanel();
        panel_17.setBackground(Color.WHITE);
        panel_Remota.add(panel_17);
        panel_17.setLayout(new BoxLayout(panel_17, 0));
        final JCheckBox chckbxNonRilevabile_5 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoAllergiaAdAltreSostanze.add(chckbxNonRilevabile_5);
        chckbxNonRilevabile_5.setBackground(Color.WHITE);
        panel_17.add(chckbxNonRilevabile_5);
        final JCheckBox chckbxNo_8 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoAllergiaAdAltreSostanze.add(chckbxNo_8);
        chckbxNo_8.setBackground(Color.WHITE);
        panel_17.add(chckbxNo_8);
        final JPanel panel_18 = new JPanel();
        panel_18.setBackground(Color.WHITE);
        panel_Remota.add(panel_18);
        panel_18.setLayout(new BoxLayout(panel_18, 0));
        final JCheckBox chckbxNonRicorda_2 = new JCheckBox("NON RICORDA");
        FrameCartellaClinicaModel.gruppoAllergiaAdAltreSostanze.add(chckbxNonRicorda_2);
        chckbxNonRicorda_2.setBackground(Color.WHITE);
        panel_18.add(chckbxNonRicorda_2);
        final JCheckBox chckbxSi_8 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoAllergiaAdAltreSostanze.add(chckbxSi_8);
        chckbxSi_8.setBackground(Color.WHITE);
        panel_18.add(chckbxSi_8);
        final JPanel panel_19 = new JPanel();
        panel_19.setBackground(Color.WHITE);
        panel_Remota.add(panel_19);
        panel_19.setLayout(new BoxLayout(panel_19, 0));
        this.textAreaAllergiaAdAltreSostanze = new JTextArea();
        final JScrollPane scrollPane_4 = new JScrollPane(this.textAreaAllergiaAdAltreSostanze);
        panel_19.add(scrollPane_4);
        final JLabel lblAllergiaNotaA = new JLabel(" Allergia nota a farmaci: ");
        lblAllergiaNotaA.setFont(new Font("Tahoma", 1, 11));
        panel_Remota.add(lblAllergiaNotaA);
        final JPanel panel_20 = new JPanel();
        panel_20.setBackground(Color.WHITE);
        panel_Remota.add(panel_20);
        panel_20.setLayout(new BoxLayout(panel_20, 0));
        final JCheckBox chckbxNonRilevabile_6 = new JCheckBox("NON RILEVABILE");
        FrameCartellaClinicaModel.gruppoAllergiaNotaAFarmaci.add(chckbxNonRilevabile_6);
        chckbxNonRilevabile_6.setBackground(Color.WHITE);
        panel_20.add(chckbxNonRilevabile_6);
        final JCheckBox chckbxNo_9 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoAllergiaNotaAFarmaci.add(chckbxNo_9);
        chckbxNo_9.setBackground(Color.WHITE);
        panel_20.add(chckbxNo_9);
        final JPanel panel_21 = new JPanel();
        panel_21.setBackground(Color.WHITE);
        panel_Remota.add(panel_21);
        panel_21.setLayout(new BoxLayout(panel_21, 0));
        final JCheckBox chckbxNonRicorda_3 = new JCheckBox("NON RICORDA");
        FrameCartellaClinicaModel.gruppoAllergiaNotaAFarmaci.add(chckbxNonRicorda_3);
        chckbxNonRicorda_3.setBackground(Color.WHITE);
        panel_21.add(chckbxNonRicorda_3);
        final JCheckBox chckbxNo_10 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoAllergiaNotaAFarmaci.add(chckbxNo_10);
        chckbxNo_10.setBackground(Color.WHITE);
        panel_21.add(chckbxNo_10);
        final JPanel panel_22 = new JPanel();
        panel_22.setBackground(Color.WHITE);
        panel_Remota.add(panel_22);
        panel_22.setLayout(new BoxLayout(panel_22, 0));
        this.textAreaAllergiaNotaAFarmaci = new JTextArea();
        final JScrollPane scrollPane_5 = new JScrollPane(this.textAreaAllergiaNotaAFarmaci);
        panel_22.add(scrollPane_5);
        final Component verticalStrut_3 = Box.createVerticalStrut(20);
        this.panel_ValutazioneClinicaIniziale.add(verticalStrut_3);
        final JPanel panel_AnamnesiFutura = new JPanel();
        panel_AnamnesiFutura.setBackground(Color.WHITE);
        this.panel_ValutazioneClinicaIniziale.add(panel_AnamnesiFutura);
        panel_AnamnesiFutura.setLayout(new BoxLayout(panel_AnamnesiFutura, 0));
        final JLabel lblAnamnesiPatologicaProssima = new JLabel("ANAMNESI PATOLOGICA PROSSIMA");
        panel_AnamnesiFutura.add(lblAnamnesiPatologicaProssima);
        lblAnamnesiPatologicaProssima.setFont(new Font("Tahoma", 1, 11));
        final Component horizontalStrut_20 = Box.createHorizontalStrut(5);
        panel_AnamnesiFutura.add(horizontalStrut_20);
        final JPanel panel_23 = new JPanel();
        panel_AnamnesiFutura.add(panel_23);
        panel_23.setBackground(Color.WHITE);
        panel_23.setLayout(new BoxLayout(panel_23, 0));
        (this.textAreaAnamnesiPatologicaProssima = new JTextArea()).setBorder(new LineBorder(Color.DARK_GRAY));
        final JScrollPane scrollPane_6 = new JScrollPane(this.textAreaAnamnesiPatologicaProssima);
        panel_23.add(scrollPane_6);
    }
    
    private void creaPannelloValutazioneInizialeInfermieristica(final Paziente p1) {
        (this.panel_ValutazioneInizialeInfermieristica = new JPanel()).setBackground(Color.WHITE);
        this.panel_ValutazioneInizialeInfermieristica.setLayout(new BoxLayout(this.panel_ValutazioneInizialeInfermieristica, 1));
        final JPanel panel_ParametriVitali = new JPanel();
        panel_ParametriVitali.setBackground(Color.WHITE);
        this.panel_ValutazioneInizialeInfermieristica.add(panel_ParametriVitali);
        final JLabel lblParametriVitali = new JLabel("PARAMETRI VITALI");
        lblParametriVitali.setFont(new Font("Tahoma", 1, 18));
        lblParametriVitali.setBackground(Color.WHITE);
        panel_ParametriVitali.add(lblParametriVitali);
        final JPanel panel_Temperatura = new JPanel();
        panel_Temperatura.setBackground(Color.WHITE);
        this.panel_ValutazioneInizialeInfermieristica.add(panel_Temperatura);
        final JLabel lblTemperatura = new JLabel(" Temperatura:  ");
        lblTemperatura.setFont(new Font("Tahoma", 1, 11));
        lblTemperatura.setBackground(Color.WHITE);
        panel_Temperatura.add(lblTemperatura);
        final JCheckBox chckbxAfebbrile = new JCheckBox("Afebbrile");
        chckbxAfebbrile.setBackground(Color.WHITE);
        panel_Temperatura.add(chckbxAfebbrile);
        final Component horizontalStrut_5 = Box.createHorizontalStrut(20);
        panel_Temperatura.add(horizontalStrut_5);
        final JLabel lblFebbrile = new JLabel("Febbrile");
        panel_Temperatura.add(lblFebbrile);
        (this.textFieldTemperaturaFebbrile = new JTextField()).setDocument(new LimitedTextField(3));
        panel_Temperatura.add(this.textFieldTemperaturaFebbrile);
        this.textFieldTemperaturaFebbrile.setColumns(3);
        final JLabel lblc = new JLabel("°C");
        panel_Temperatura.add(lblc);
        final JPanel panel_Parametri = new JPanel();
        panel_Parametri.setBackground(Color.WHITE);
        this.panel_ValutazioneInizialeInfermieristica.add(panel_Parametri);
        final JLabel lblParametriVitali_1 = new JLabel("Parametri vitali: ");
        lblParametriVitali_1.setFont(new Font("Tahoma", 1, 11));
        panel_Parametri.add(lblParametriVitali_1);
        final JLabel lblF = new JLabel("F");
        lblF.setFont(new Font("Tahoma", 0, 11));
        panel_Parametri.add(lblF);
        (this.textFieldFPerMinuti = new JTextField()).setDocument(new LimitedTextField(3));
        panel_Parametri.add(this.textFieldFPerMinuti);
        this.textFieldFPerMinuti.setColumns(4);
        final JLabel lblBm = new JLabel("b/m");
        lblBm.setFont(new Font("Tahoma", 0, 11));
        panel_Parametri.add(lblBm);
        final Component horizontalStrut_6 = Box.createHorizontalStrut(10);
        panel_Parametri.add(horizontalStrut_6);
        final JLabel lblPa = new JLabel("PA");
        panel_Parametri.add(lblPa);
        (this.textFieldPressioneArteriosa = new JTextField()).setDocument(new LimitedTextField(3));
        panel_Parametri.add(this.textFieldPressioneArteriosa);
        this.textFieldPressioneArteriosa.setColumns(5);
        final JLabel lblMmhg = new JLabel("mmHg");
        panel_Parametri.add(lblMmhg);
        final Component horizontalStrut_7 = Box.createHorizontalStrut(10);
        panel_Parametri.add(horizontalStrut_7);
        final JLabel lblSpo = new JLabel("SpO2");
        panel_Parametri.add(lblSpo);
        (this.textFieldSpO2 = new JTextField()).setDocument(new LimitedTextField(3));
        panel_Parametri.add(this.textFieldSpO2);
        this.textFieldSpO2.setColumns(4);
        final JLabel label_1 = new JLabel("%");
        panel_Parametri.add(label_1);
        final Component horizontalStrut_8 = Box.createHorizontalStrut(10);
        panel_Parametri.add(horizontalStrut_8);
        final JLabel lblFrequenzaCardiaca = new JLabel("Frequenza cardiaca: atti");
        panel_Parametri.add(lblFrequenzaCardiaca);
        (this.textFieldFrequenzaCardiaca = new JTextField()).setDocument(new LimitedTextField(4));
        panel_Parametri.add(this.textFieldFrequenzaCardiaca);
        this.textFieldFrequenzaCardiaca.setColumns(4);
        final JLabel lblmin = new JLabel("/min");
        panel_Parametri.add(lblmin);
        final Component horizontalStrut_9 = Box.createHorizontalStrut(10);
        panel_Parametri.add(horizontalStrut_9);
        final JLabel lblHgt = new JLabel("HGT");
        panel_Parametri.add(lblHgt);
        (this.textFieldHGT = new JTextField()).setDocument(new LimitedTextField(3));
        panel_Parametri.add(this.textFieldHGT);
        this.textFieldHGT.setColumns(4);
        final JLabel lblMgdl = new JLabel("mg/dl");
        panel_Parametri.add(lblMgdl);
        final JPanel panel_ScreeningDolore = new JPanel();
        panel_ScreeningDolore.setBackground(Color.WHITE);
        this.panel_ValutazioneInizialeInfermieristica.add(panel_ScreeningDolore);
        panel_ScreeningDolore.setLayout(new BoxLayout(panel_ScreeningDolore, 0));
        final JLabel lblScreeningDolore = new JLabel("Screening dolore:");
        lblScreeningDolore.setFont(new Font("Tahoma", 1, 11));
        panel_ScreeningDolore.add(lblScreeningDolore);
        final JCheckBox chckbxNonRilevabile = new JCheckBox("NON RILEVABILE ");
        chckbxNonRilevabile.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoScreeningDolore.add(chckbxNonRilevabile);
        panel_ScreeningDolore.add(chckbxNonRilevabile);
        final JCheckBox chckbxAssenzaDiDolore = new JCheckBox("ASSENZA DI DOLORE");
        chckbxAssenzaDiDolore.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoScreeningDolore.add(chckbxAssenzaDiDolore);
        panel_ScreeningDolore.add(chckbxAssenzaDiDolore);
        final Component horizontalStrut_10 = Box.createHorizontalStrut(10);
        panel_ScreeningDolore.add(horizontalStrut_10);
        final JLabel lblDolore = new JLabel("DOLORE");
        lblDolore.setFont(new Font("Tahoma", 0, 11));
        lblDolore.setBackground(Color.WHITE);
        panel_ScreeningDolore.add(lblDolore);
        final JPanel panel_11 = new JPanel();
        panel_11.setBackground(Color.WHITE);
        panel_ScreeningDolore.add(panel_11);
        panel_11.setLayout(new BoxLayout(panel_11, 0));
        final JRadioButton radioButton = new JRadioButton("1");
        radioButton.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoScalaDolore.add(radioButton);
        panel_11.add(radioButton);
        final JRadioButton radioButton_1 = new JRadioButton("2");
        radioButton_1.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoScalaDolore.add(radioButton_1);
        panel_11.add(radioButton_1);
        final JRadioButton radioButton_2 = new JRadioButton("3");
        radioButton_2.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoScalaDolore.add(radioButton_2);
        panel_11.add(radioButton_2);
        final JRadioButton radioButton_3 = new JRadioButton("4");
        radioButton_3.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoScalaDolore.add(radioButton_3);
        panel_11.add(radioButton_3);
        final JRadioButton radioButton_4 = new JRadioButton("5");
        radioButton_4.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoScalaDolore.add(radioButton_4);
        panel_11.add(radioButton_4);
        final JRadioButton radioButton_5 = new JRadioButton("6");
        radioButton_5.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoScalaDolore.add(radioButton_5);
        panel_11.add(radioButton_5);
        final JRadioButton radioButton_6 = new JRadioButton("7");
        radioButton_6.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoScalaDolore.add(radioButton_6);
        panel_11.add(radioButton_6);
        final JRadioButton radioButton_7 = new JRadioButton("8");
        radioButton_7.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoScalaDolore.add(radioButton_7);
        panel_11.add(radioButton_7);
        final JRadioButton radioButton_8 = new JRadioButton("9");
        radioButton_8.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoScalaDolore.add(radioButton_8);
        panel_11.add(radioButton_8);
        final JRadioButton radioButton_9 = new JRadioButton("10");
        radioButton_9.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoScalaDolore.add(radioButton_9);
        panel_11.add(radioButton_9);
        final JPanel panel_EsameFattori = new JPanel();
        panel_EsameFattori.setBackground(Color.WHITE);
        this.panel_ValutazioneInizialeInfermieristica.add(panel_EsameFattori);
        final JLabel lblEsameDeiFattori = new JLabel("ESAME DEI FATTORI");
        lblEsameDeiFattori.setFont(new Font("Tahoma", 1, 18));
        panel_EsameFattori.add(lblEsameDeiFattori);
        final JPanel panel_FumoAlcol = new JPanel();
        panel_FumoAlcol.setBackground(Color.WHITE);
        this.panel_ValutazioneInizialeInfermieristica.add(panel_FumoAlcol);
        final JLabel lblFumatore = new JLabel("Fumatore: ");
        lblFumatore.setFont(new Font("Tahoma", 1, 11));
        panel_FumoAlcol.add(lblFumatore);
        final JCheckBox chckbxNo = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoFumatore.add(chckbxNo);
        chckbxNo.setBackground(Color.WHITE);
        panel_FumoAlcol.add(chckbxNo);
        final JCheckBox chckbxSi = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoFumatore.add(chckbxSi);
        chckbxSi.setBackground(Color.WHITE);
        panel_FumoAlcol.add(chckbxSi);
        final Component horizontalStrut_11 = Box.createHorizontalStrut(5);
        panel_FumoAlcol.add(horizontalStrut_11);
        final JLabel lblNsigarettedie = new JLabel("n.sigarette/die");
        panel_FumoAlcol.add(lblNsigarettedie);
        (this.textFieldNumSigaretteDie = new JTextField()).setDocument(new LimitedTextField(3));
        panel_FumoAlcol.add(this.textFieldNumSigaretteDie);
        this.textFieldNumSigaretteDie.setColumns(3);
        final Component horizontalStrut_12 = Box.createHorizontalStrut(20);
        panel_FumoAlcol.add(horizontalStrut_12);
        final JLabel lblUsoDiAlcool = new JLabel("Uso di alcool: ");
        lblUsoDiAlcool.setFont(new Font("Tahoma", 1, 11));
        panel_FumoAlcol.add(lblUsoDiAlcool);
        final JCheckBox chckbxNo_1 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoUsoDiAlcool.add(chckbxNo_1);
        chckbxNo_1.setBackground(Color.WHITE);
        panel_FumoAlcol.add(chckbxNo_1);
        final JCheckBox chckbxSi_1 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoUsoDiAlcool.add(chckbxSi_1);
        chckbxSi_1.setBackground(Color.WHITE);
        panel_FumoAlcol.add(chckbxSi_1);
        final Component horizontalStrut_13 = Box.createHorizontalStrut(5);
        panel_FumoAlcol.add(horizontalStrut_13);
        final JLabel lblQuantitdie = new JLabel("quantit\u00e0/die");
        panel_FumoAlcol.add(lblQuantitdie);
        (this.textFieldQuantitaAlcoolDie = new JTextField()).setDocument(new LimitedTextField(5));
        panel_FumoAlcol.add(this.textFieldQuantitaAlcoolDie);
        this.textFieldQuantitaAlcoolDie.setColumns(5);
        final JPanel panel_Igiene = new JPanel();
        panel_Igiene.setBackground(Color.WHITE);
        this.panel_ValutazioneInizialeInfermieristica.add(panel_Igiene);
        final JLabel lblIgienePersonale = new JLabel("Igiene personale: ");
        lblIgienePersonale.setFont(new Font("Tahoma", 1, 11));
        panel_Igiene.add(lblIgienePersonale);
        final JCheckBox chckbxAutonoma = new JCheckBox("autonoma");
        FrameCartellaClinicaModel.gruppoIgienePersonale.add(chckbxAutonoma);
        chckbxAutonoma.setBackground(Color.WHITE);
        panel_Igiene.add(chckbxAutonoma);
        final JCheckBox chckbxAssistita = new JCheckBox("assistita");
        FrameCartellaClinicaModel.gruppoIgienePersonale.add(chckbxAssistita);
        chckbxAssistita.setBackground(Color.WHITE);
        panel_Igiene.add(chckbxAssistita);
        final JCheckBox chckbxTotalmenteDipendente = new JCheckBox("totalmente dipendente");
        FrameCartellaClinicaModel.gruppoIgienePersonale.add(chckbxTotalmenteDipendente);
        chckbxTotalmenteDipendente.setBackground(Color.WHITE);
        panel_Igiene.add(chckbxTotalmenteDipendente);
        final JPanel panel_StatoEmotivo = new JPanel();
        panel_StatoEmotivo.setBackground(Color.WHITE);
        this.panel_ValutazioneInizialeInfermieristica.add(panel_StatoEmotivo);
        final JLabel lblStatoEmotivo = new JLabel("Stato emotivo: ");
        lblStatoEmotivo.setFont(new Font("Tahoma", 1, 11));
        panel_StatoEmotivo.add(lblStatoEmotivo);
        final JCheckBox chckbxTranquillo = new JCheckBox("tranquillo");
        FrameCartellaClinicaModel.gruppoStatoEmotivo.add(chckbxTranquillo);
        chckbxTranquillo.setBackground(Color.WHITE);
        panel_StatoEmotivo.add(chckbxTranquillo);
        final JCheckBox chckbxApprensivo = new JCheckBox("apprensivo");
        FrameCartellaClinicaModel.gruppoStatoEmotivo.add(chckbxApprensivo);
        chckbxApprensivo.setBackground(Color.WHITE);
        panel_StatoEmotivo.add(chckbxApprensivo);
        final JCheckBox chckbxIrrequieto = new JCheckBox("irrequieto");
        FrameCartellaClinicaModel.gruppoStatoEmotivo.add(chckbxIrrequieto);
        chckbxIrrequieto.setBackground(Color.WHITE);
        panel_StatoEmotivo.add(chckbxIrrequieto);
        final Component horizontalStrut_14 = Box.createHorizontalStrut(20);
        panel_StatoEmotivo.add(horizontalStrut_14);
        final JLabel lblCaratteristicheDelSonno = new JLabel("Caratteristiche del sonno: ");
        lblCaratteristicheDelSonno.setFont(new Font("Tahoma", 1, 11));
        panel_StatoEmotivo.add(lblCaratteristicheDelSonno);
        final JCheckBox chckbxRegolare = new JCheckBox("regolare");
        FrameCartellaClinicaModel.gruppoCaratteristicheDelSonno.add(chckbxRegolare);
        chckbxRegolare.setBackground(Color.WHITE);
        panel_StatoEmotivo.add(chckbxRegolare);
        final JCheckBox chckbxInsonnia = new JCheckBox("insonnia");
        FrameCartellaClinicaModel.gruppoCaratteristicheDelSonno.add(chckbxInsonnia);
        chckbxInsonnia.setBackground(Color.WHITE);
        panel_StatoEmotivo.add(chckbxInsonnia);
        final JPanel panel_Movimento = new JPanel();
        panel_Movimento.setBackground(Color.WHITE);
        this.panel_ValutazioneInizialeInfermieristica.add(panel_Movimento);
        final JLabel lblMovimento = new JLabel("Movimento: ");
        lblMovimento.setFont(new Font("Tahoma", 1, 11));
        panel_Movimento.add(lblMovimento);
        final JCheckBox chckbxAutonomo = new JCheckBox("Autonomo");
        FrameCartellaClinicaModel.gruppoMovimento.add(chckbxAutonomo);
        chckbxAutonomo.setBackground(Color.WHITE);
        panel_Movimento.add(chckbxAutonomo);
        final JCheckBox chckbxAssistito = new JCheckBox("Assistito");
        FrameCartellaClinicaModel.gruppoMovimento.add(chckbxAssistito);
        chckbxAssistito.setBackground(Color.WHITE);
        panel_Movimento.add(chckbxAssistito);
        final JCheckBox chckbxConAusili = new JCheckBox("Con ausili");
        FrameCartellaClinicaModel.gruppoMovimento.add(chckbxConAusili);
        chckbxConAusili.setBackground(Color.WHITE);
        panel_Movimento.add(chckbxConAusili);
        final JCheckBox chckbxAllettato = new JCheckBox("Allettato");
        FrameCartellaClinicaModel.gruppoMovimento.add(chckbxAllettato);
        chckbxAllettato.setBackground(Color.WHITE);
        panel_Movimento.add(chckbxAllettato);
        final JCheckBox chckbxMantieneLaPostura = new JCheckBox("Mantiene la postura");
        FrameCartellaClinicaModel.gruppoMovimento.add(chckbxMantieneLaPostura);
        chckbxMantieneLaPostura.setBackground(Color.WHITE);
        panel_Movimento.add(chckbxMantieneLaPostura);
        final JCheckBox chckbxNonMantieneLa = new JCheckBox("Non mantiene la postura");
        FrameCartellaClinicaModel.gruppoMovimento.add(chckbxNonMantieneLa);
        chckbxNonMantieneLa.setBackground(Color.WHITE);
        panel_Movimento.add(chckbxNonMantieneLa);
        final JPanel panel_Protesi = new JPanel();
        panel_Protesi.setBackground(Color.WHITE);
        this.panel_ValutazioneInizialeInfermieristica.add(panel_Protesi);
        final JLabel lblPortatoreDiProtesi = new JLabel("Portatore di protesi: ");
        lblPortatoreDiProtesi.setBackground(Color.WHITE);
        lblPortatoreDiProtesi.setFont(new Font("Tahoma", 1, 11));
        panel_Protesi.add(lblPortatoreDiProtesi);
        final JCheckBox chckbxNo_2 = new JCheckBox("NO");
        FrameCartellaClinicaModel.gruppoPortatoreDiProtesi.add(chckbxNo_2);
        chckbxNo_2.setBackground(Color.WHITE);
        panel_Protesi.add(chckbxNo_2);
        final JCheckBox chckbxSi_2 = new JCheckBox("SI");
        FrameCartellaClinicaModel.gruppoPortatoreDiProtesi.add(chckbxSi_2);
        chckbxSi_2.setBackground(Color.WHITE);
        panel_Protesi.add(chckbxSi_2);
        (this.textFieldPortatoreDiProtesiSi = new JTextField()).setDocument(new LimitedTextField(30));
        panel_Protesi.add(this.textFieldPortatoreDiProtesiSi);
        this.textFieldPortatoreDiProtesiSi.setColumns(20);
        final JPanel panel_Alimentazione = new JPanel();
        panel_Alimentazione.setBackground(Color.WHITE);
        this.panel_ValutazioneInizialeInfermieristica.add(panel_Alimentazione);
        final JLabel lblAlimentazione = new JLabel("Alimentazione: ");
        lblAlimentazione.setFont(new Font("Tahoma", 1, 11));
        lblAlimentazione.setBackground(Color.WHITE);
        panel_Alimentazione.add(lblAlimentazione);
        final JCheckBox chckbxAutonoma_1 = new JCheckBox("Autonoma");
        FrameCartellaClinicaModel.gruppoAlimentazione.add(chckbxAutonoma_1);
        chckbxAutonoma_1.setBackground(Color.WHITE);
        panel_Alimentazione.add(chckbxAutonoma_1);
        final JCheckBox chckbxAssistita_1 = new JCheckBox("Assistita");
        FrameCartellaClinicaModel.gruppoAlimentazione.add(chckbxAssistita_1);
        chckbxAssistita_1.setBackground(Color.WHITE);
        panel_Alimentazione.add(chckbxAssistita_1);
        final JCheckBox chckbxSoloAssistenzaDiretta = new JCheckBox("Solo assistenza diretta");
        FrameCartellaClinicaModel.gruppoAlimentazione.add(chckbxSoloAssistenzaDiretta);
        chckbxSoloAssistenzaDiretta.setBackground(Color.WHITE);
        panel_Alimentazione.add(chckbxSoloAssistenzaDiretta);
        final JCheckBox chckbxMasticazioneLimitata = new JCheckBox("Masticazione limitata");
        FrameCartellaClinicaModel.gruppoAlimentazione.add(chckbxMasticazioneLimitata);
        chckbxMasticazioneLimitata.setBackground(Color.WHITE);
        panel_Alimentazione.add(chckbxMasticazioneLimitata);
        final JCheckBox chckbxAssente = new JCheckBox("Assente");
        FrameCartellaClinicaModel.gruppoAlimentazione.add(chckbxAssente);
        chckbxAssente.setBackground(Color.WHITE);
        panel_Alimentazione.add(chckbxAssente);
        final JCheckBox chckbxUlcerazioniBocca = new JCheckBox("Ulcerazioni bocca");
        FrameCartellaClinicaModel.gruppoAlimentazione.add(chckbxUlcerazioniBocca);
        chckbxUlcerazioniBocca.setBackground(Color.WHITE);
        panel_Alimentazione.add(chckbxUlcerazioniBocca);
        final JCheckBox chckbxDeglutizioneDifficile = new JCheckBox("Deglutizione difficile");
        FrameCartellaClinicaModel.gruppoAlimentazione.add(chckbxDeglutizioneDifficile);
        chckbxDeglutizioneDifficile.setBackground(Color.WHITE);
        panel_Alimentazione.add(chckbxDeglutizioneDifficile);
        final JCheckBox chckbxProtesiDentaria = new JCheckBox("Protesi dentaria");
        FrameCartellaClinicaModel.gruppoAlimentazione.add(chckbxProtesiDentaria);
        chckbxProtesiDentaria.setBackground(Color.WHITE);
        panel_Alimentazione.add(chckbxProtesiDentaria);
        final JCheckBox chckbxDeglutizioneDolorosa = new JCheckBox("Deglutizione dolorosa");
        FrameCartellaClinicaModel.gruppoAlimentazione.add(chckbxDeglutizioneDolorosa);
        chckbxDeglutizioneDolorosa.setBackground(Color.WHITE);
        panel_Alimentazione.add(chckbxDeglutizioneDolorosa);
        final JCheckBox chckbxNutrizioneEnterale = new JCheckBox("Nutrizione enterale");
        FrameCartellaClinicaModel.gruppoAlimentazione.add(chckbxNutrizioneEnterale);
        chckbxNutrizioneEnterale.setBackground(Color.WHITE);
        panel_Alimentazione.add(chckbxNutrizioneEnterale);
        final JCheckBox chckbxNutrizioneParenterale = new JCheckBox("Nutrizione parenterale");
        FrameCartellaClinicaModel.gruppoAlimentazione.add(chckbxNutrizioneParenterale);
        chckbxNutrizioneParenterale.setBackground(Color.WHITE);
        panel_Alimentazione.add(chckbxNutrizioneParenterale);
    }
    
    private void creaPannelloAccettazione(final Paziente p1) {
        (this.panel_Accettazione = new JPanel()).setLayout(new BoxLayout(this.panel_Accettazione, 1));
        final JPanel panel_TestataCC = new JPanel();
        panel_TestataCC.setBackground(Color.WHITE);
        this.panel_Accettazione.add(panel_TestataCC);
        final JLabel lblCartellaClinica = new JLabel("CARTELLA CLINICA");
        lblCartellaClinica.setFont(new Font("Tahoma", 1, 22));
        panel_TestataCC.add(lblCartellaClinica);
        final JPanel panel_UnitaOperativa = new JPanel();
        panel_UnitaOperativa.setBackground(Color.WHITE);
        this.panel_Accettazione.add(panel_UnitaOperativa);
        final JLabel lblUnitOperativa = new JLabel("Unita' Operativa ");
        lblUnitOperativa.setFont(new Font("Tahoma", 1, 11));
        panel_UnitaOperativa.add(lblUnitOperativa);
        (this.textField = new JTextField(p1.getTipoReparto().getNomeReparto())).setBackground(Color.WHITE);
        this.textField.setEditable(false);
        panel_UnitaOperativa.add(this.textField);
        this.textField.setColumns(50);
        final JPanel panel_DirettoreResponabile = new JPanel();
        panel_DirettoreResponabile.setBackground(Color.WHITE);
        this.panel_Accettazione.add(panel_DirettoreResponabile);
        final JLabel lblNewLabel = new JLabel("Direttore/Responsabile");
        lblNewLabel.setFont(new Font("Tahoma", 1, 11));
        panel_DirettoreResponabile.add(lblNewLabel);
        (this.textFieldDirettoreResponsabile = new JTextField()).setDocument(new LimitedTextField(20));
        panel_DirettoreResponabile.add(this.textFieldDirettoreResponsabile);
        this.textFieldDirettoreResponsabile.setColumns(50);
        final JPanel panel_RegimeRicovero = new JPanel();
        panel_RegimeRicovero.setBackground(Color.WHITE);
        this.panel_Accettazione.add(panel_RegimeRicovero);
        final JLabel lblRegimeDiRicovero = new JLabel("Regime di ricovero:");
        lblRegimeDiRicovero.setFont(new Font("Tahoma", 1, 11));
        panel_RegimeRicovero.add(lblRegimeDiRicovero);
        final JCheckBox chckbxOrdinario = new JCheckBox("Ordinario");
        chckbxOrdinario.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoRegimeDiRicovero.add(chckbxOrdinario);
        panel_RegimeRicovero.add(chckbxOrdinario);
        final JCheckBox chckbxDay = new JCheckBox("Day Hospital / Day Surgery");
        chckbxDay.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoRegimeDiRicovero.add(chckbxDay);
        panel_RegimeRicovero.add(chckbxDay);
        final JCheckBox chckbxService = new JCheckBox("Day Service");
        chckbxService.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoRegimeDiRicovero.add(chckbxService);
        panel_RegimeRicovero.add(chckbxService);
        final JPanel panel_Provenienza = new JPanel();
        panel_Provenienza.setBackground(Color.WHITE);
        this.panel_Accettazione.add(panel_Provenienza);
        final JLabel lblNewLabel_1 = new JLabel("Proveniente da:");
        lblNewLabel_1.setFont(new Font("Tahoma", 1, 11));
        panel_Provenienza.add(lblNewLabel_1);
        final JCheckBox chckbxDomicilio = new JCheckBox("Domicilio");
        chckbxDomicilio.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoProvenienteDa.add(chckbxDomicilio);
        panel_Provenienza.add(chckbxDomicilio);
        final JCheckBox chckbxRsa_1 = new JCheckBox("R.S.A.");
        chckbxRsa_1.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoProvenienteDa.add(chckbxRsa_1);
        panel_Provenienza.add(chckbxRsa_1);
        final JCheckBox chckbxPs_1 = new JCheckBox("P.S.");
        chckbxPs_1.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoProvenienteDa.add(chckbxPs_1);
        panel_Provenienza.add(chckbxPs_1);
        final JCheckBox chckbxAltroOspedale = new JCheckBox("altro Ospedale");
        chckbxAltroOspedale.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoProvenienteDa.add(chckbxAltroOspedale);
        panel_Provenienza.add(chckbxAltroOspedale);
        final JCheckBox chckbxAltro = new JCheckBox("altro");
        chckbxAltro.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoProvenienteDa.add(chckbxAltro);
        panel_Provenienza.add(chckbxAltro);
        (this.textFieldProvenienteDaAltro = new JTextField()).setDocument(new LimitedTextField(20));
        panel_Provenienza.add(this.textFieldProvenienteDaAltro);
        this.textFieldProvenienteDaAltro.setColumns(20);
        final JPanel panel_Dati1 = new JPanel();
        panel_Dati1.setBackground(Color.WHITE);
        this.panel_Accettazione.add(panel_Dati1);
        final JLabel lblCognome = new JLabel("Cognome ");
        lblCognome.setFont(new Font("Tahoma", 1, 11));
        panel_Dati1.add(lblCognome);
        (this.textField_Cognome = new JTextField()).setText(p1.getCognome());
        this.textField_Cognome.setEditable(false);
        this.textField_Cognome.setBackground(Color.WHITE);
        this.textField_Cognome.setColumns(p1.getCognome().length());
        panel_Dati1.add(this.textField_Cognome);
        final Component horizontalStrut = Box.createHorizontalStrut(20);
        panel_Dati1.add(horizontalStrut);
        final JLabel lblNome = new JLabel("Nome ");
        lblNome.setFont(new Font("Tahoma", 1, 11));
        panel_Dati1.add(lblNome);
        (this.textField_Nome = new JTextField()).setText(p1.getNome());
        this.textField_Nome.setEditable(false);
        this.textField_Nome.setBackground(Color.WHITE);
        this.textField_Nome.setColumns(p1.getNome().length());
        panel_Dati1.add(this.textField_Nome);
        final Component horizontalStrut_1 = Box.createHorizontalStrut(20);
        panel_Dati1.add(horizontalStrut_1);
        final JLabel lblSesso = new JLabel("Sesso ");
        lblSesso.setFont(new Font("Tahoma", 1, 11));
        panel_Dati1.add(lblSesso);
        final String[] array = { p1.getGender() };
        final JComboBox<String> comboBox = new JComboBox<String>(array);
        comboBox.setEditable(false);
        comboBox.setBackground(Color.WHITE);
        panel_Dati1.add(comboBox);
        final Component horizontalStrut_2 = Box.createHorizontalStrut(20);
        panel_Dati1.add(horizontalStrut_2);
        final JLabel lblCodiceFiscale = new JLabel("Codice Fiscale");
        lblCodiceFiscale.setFont(new Font("Tahoma", 1, 11));
        panel_Dati1.add(lblCodiceFiscale);
        (this.textField_CF = new JTextField()).setText(p1.getCodFiscale().toUpperCase());
        this.textField_CF.setBackground(Color.WHITE);
        this.textField_CF.setEditable(false);
        this.textField_CF.setColumns(p1.getCodFiscale().length());
        panel_Dati1.add(this.textField_CF);
        final JPanel panel_Dati2 = new JPanel();
        panel_Dati2.setBackground(Color.WHITE);
        this.panel_Accettazione.add(panel_Dati2);
        final JLabel lblLuogoDiNascita = new JLabel("Luogo di nascita ");
        lblLuogoDiNascita.setFont(new Font("Tahoma", 1, 11));
        panel_Dati2.add(lblLuogoDiNascita);
        (this.textFieldLuogoDiNascita = new JTextField()).setDocument(new LimitedTextField(20));
        this.textFieldLuogoDiNascita.setBackground(Color.WHITE);
        panel_Dati2.add(this.textFieldLuogoDiNascita);
        this.textFieldLuogoDiNascita.setColumns(20);
        final Component horizontalStrut_3 = Box.createHorizontalStrut(20);
        panel_Dati2.add(horizontalStrut_3);
        final JLabel lblNewLabel_2 = new JLabel("(Prov.");
        lblNewLabel_2.setFont(new Font("Tahoma", 1, 11));
        panel_Dati2.add(lblNewLabel_2);
        (this.textFieldProvincia = new JTextField()).setBackground(Color.WHITE);
        this.textFieldProvincia.setColumns(4);
        this.textFieldProvincia.setDocument(new LimitedTextField(2));
        panel_Dati2.add(this.textFieldProvincia);
        final JLabel label = new JLabel(")");
        label.setFont(new Font("Tahoma", 1, 11));
        panel_Dati2.add(label);
        final Component horizontalStrut_4 = Box.createHorizontalStrut(20);
        panel_Dati2.add(horizontalStrut_4);
        final JLabel lblDataDiNascita = new JLabel("Data di nascita");
        lblDataDiNascita.setFont(new Font("Tahoma", 1, 11));
        lblDataDiNascita.setBackground(Color.WHITE);
        panel_Dati2.add(lblDataDiNascita);
        (this.textField_DataDiNascita = new JTextField()).setText(p1.getDataDiNascita());
        this.textField_DataDiNascita.setColumns(p1.getDataDiNascita().length());
        this.textField_DataDiNascita.setBackground(Color.WHITE);
        this.textField_DataDiNascita.setEditable(false);
        panel_Dati2.add(this.textField_DataDiNascita);
        final JPanel panel_DiagnosiInterventi = new JPanel();
        panel_DiagnosiInterventi.setBackground(Color.WHITE);
        this.panel_Accettazione.add(panel_DiagnosiInterventi);
        panel_DiagnosiInterventi.setLayout(new BorderLayout(0, 0));
        final JPanel panel_1 = new JPanel();
        panel_1.setBackground(Color.WHITE);
        panel_DiagnosiInterventi.add(panel_1, "Center");
        panel_1.setLayout(this.cardLayoutTextArea);
        final JPanel panel_2 = new JPanel();
        panel_2.setBackground(Color.WHITE);
        (this.textAreaDiagnosiDIngresso = new JTextArea()).setBorder(new LineBorder(Color.BLACK, 2, true));
        final JScrollPane sp = new JScrollPane(this.textAreaDiagnosiDIngresso);
        panel_2.add(sp);
        panel_2.setLayout(new BoxLayout(panel_2, 0));
        final JPanel panel_3 = new JPanel();
        panel_3.setBackground(Color.WHITE);
        (this.textAreaInterventiChirurgici = new JTextArea()).setBorder(new LineBorder(Color.RED, 2, true));
        final JScrollPane scrollPane = new JScrollPane(this.textAreaInterventiChirurgici);
        panel_3.add(scrollPane);
        panel_3.setLayout(new BoxLayout(panel_3, 0));
        final JPanel panel_4 = new JPanel();
        panel_4.setBackground(Color.WHITE);
        (this.textAreaDignosiDiDimissione = new JTextArea()).setBorder(new LineBorder(Color.GREEN, 2, true));
        final JScrollPane scrollPane_1 = new JScrollPane(this.textAreaDignosiDiDimissione);
        panel_4.add(scrollPane_1);
        panel_4.setLayout(new BoxLayout(panel_4, 0));
        panel_1.add(panel_2, "1");
        panel_1.add(panel_3, "2");
        panel_1.add(panel_4, "3");
        final JPanel panel_5 = new JPanel();
        panel_DiagnosiInterventi.add(panel_5, "West");
        panel_5.setLayout(new BoxLayout(panel_5, 1));
        final JPanel panel_6 = new JPanel();
        panel_6.setBackground(Color.WHITE);
        panel_5.add(panel_6);
        panel_6.setLayout(new GridLayout(0, 1, 0, 0));
        final JToggleButton tglbtnDiagnosiDingresso = new JToggleButton("Diagnosi d'ingresso");
        tglbtnDiagnosiDingresso.setFont(new Font("Tahoma", 1, 11));
        FrameCartellaClinicaModel.buttonGroup_1.add(tglbtnDiagnosiDingresso);
        tglbtnDiagnosiDingresso.setBackground(Color.WHITE);
        panel_6.add(tglbtnDiagnosiDingresso);
        final JPanel panel_7 = new JPanel();
        panel_7.setBackground(Color.WHITE);
        panel_5.add(panel_7);
        panel_7.setLayout(new GridLayout(0, 1, 0, 0));
        final JToggleButton tglbtnInterventiChirurgici = new JToggleButton("Interventi chirurgici");
        FrameCartellaClinicaModel.buttonGroup_1.add(tglbtnInterventiChirurgici);
        tglbtnInterventiChirurgici.setFont(new Font("Tahoma", 1, 11));
        tglbtnInterventiChirurgici.setBackground(Color.WHITE);
        panel_7.add(tglbtnInterventiChirurgici);
        final JPanel panel_8 = new JPanel();
        panel_8.setBackground(Color.WHITE);
        panel_5.add(panel_8);
        panel_8.setLayout(new GridLayout(0, 1, 0, 0));
        final JToggleButton tglbtnDiagnosiDiDimissione = new JToggleButton("Diagnosi di dimissione");
        FrameCartellaClinicaModel.buttonGroup_1.add(tglbtnDiagnosiDiDimissione);
        tglbtnDiagnosiDiDimissione.setFont(new Font("Tahoma", 1, 11));
        tglbtnDiagnosiDiDimissione.setBackground(Color.WHITE);
        panel_8.add(tglbtnDiagnosiDiDimissione);
        tglbtnDiagnosiDingresso.addMouseListener(new ClickECambioCard(this.cardLayoutTextArea, 1, panel_1));
        tglbtnInterventiChirurgici.addMouseListener(new ClickECambioCard(this.cardLayoutTextArea, 2, panel_1));
        tglbtnDiagnosiDiDimissione.addMouseListener(new ClickECambioCard(this.cardLayoutTextArea, 3, panel_1));
        final JPanel panel_TipoDimissione = new JPanel();
        panel_TipoDimissione.setBackground(Color.WHITE);
        this.panel_Accettazione.add(panel_TipoDimissione);
        final JCheckBox chckbxDimissioneOrdinaria = new JCheckBox("Dimissione ordinaria");
        chckbxDimissioneOrdinaria.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoTipologiaDimissione.add(chckbxDimissioneOrdinaria);
        panel_TipoDimissione.add(chckbxDimissioneOrdinaria);
        final JCheckBox chckbxDimissioneVolontaria = new JCheckBox("Dimissione volontaria");
        chckbxDimissioneVolontaria.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoTipologiaDimissione.add(chckbxDimissioneVolontaria);
        panel_TipoDimissione.add(chckbxDimissioneVolontaria);
        final JCheckBox chckbxDimissioneProtetta = new JCheckBox("Dimissione protetta");
        chckbxDimissioneProtetta.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoTipologiaDimissione.add(chckbxDimissioneProtetta);
        panel_TipoDimissione.add(chckbxDimissioneProtetta);
        final JCheckBox chckbxDimissioneFacilitata = new JCheckBox("Dimissione facilitata");
        chckbxDimissioneFacilitata.setBackground(Color.WHITE);
        FrameCartellaClinicaModel.gruppoTipologiaDimissione.add(chckbxDimissioneFacilitata);
        panel_TipoDimissione.add(chckbxDimissioneFacilitata);
    }
}
